<a href="https://colab.research.google.com/github/tkoritsidis/tkorepka/blob/main/Diabetes_exersice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0                      torcache.net        0        0           1          2   
1                   themeforest.net        0        0           1          4   
2  shibamicomzeminet.nckitennis.gdn        0        0           0          0   
3                        allegro.pl        0        0           1          1   
4          update.troyvanspanje.com        0        0           0          0   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              0           0            0   
1            0             0        0              0           0            1   
2            0             0        1              0           1            1   
3            0             0        0              0           0            1   
4            0             0        0              0           0            1   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           1           1       0           0            1             0   
1           1           1       0           0            1             0   
2           1           1       0           0            1             0   
3           1           1       0           0            1             0   
4           0           1       0           0            1             0   

   Label  
0      0  
1      0  
2      1  
3      0  
4      1

In [3]:
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          2            0             0   
1        0        0           1          4            0             0   
2        0        0           0          0            0             0   
3        0        0           1          1            0             0   
4        0        0           0          0            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            0           1           1   
1        0              0           0            1           1           1   
2        1              0           1            1           1           1   
3        0              0           0            1           1           1   
4        0              0           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [5]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [7]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [9]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8063333333333333
Precision: 0.832956429435434
Recall: 0.8063333333333333
F1 Score: 0.802289138854219
Confusion Matrix:
[[1426   78]
 [ 503  993]]

SVC Metrics:
Accuracy: 0.833
Precision: 0.8663302107487392
Recall: 0.833
F1 Score: 0.8290312723364688
Confusion Matrix:
[[1480   24]
 [ 477 1019]]

RandomForestClassifier Metrics:
Accuracy: 0.8656666666666667
Precision: 0.8761484776713693
Recall: 0.8656666666666667
F1 Score: 0.8646890606157591
Confusion Matrix:
[[1428   76]
 [ 327 1169]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.86
Precision: 0.8710949665734686
Recall: 0.86
F1 Score: 0.8589073692095675
Confusion Matrix:
[[1424   80]
 [ 340 1156]]

KNeighborsClassifier Metrics:
Accuracy: 0.8573333333333333
Precision: 0.8657322521813674
Recall: 0.8573333333333333
F1 Score: 0.8564750655463707
Confusion Matrix:
[[1404  100]
 [ 328 1168]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8636666666666667
Precision: 0.8746112098791913
Recall: 0.8636666666666667
F1 Score: 0.8626268888820453
Confusion Matrix:
[[1428   76]
 [ 333 1163]]


In [10]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.865667   0.876148  0.865667  0.864689
5  DecisionTreeClassifier  0.863667   0.874611  0.863667  0.862627
3           MLPClassifier  0.860000   0.871095  0.860000  0.858907
4    KNeighborsClassifier  0.857333   0.865732  0.857333  0.856475
1                     SVC  0.833000   0.866330  0.833000  0.829031
0      LogisticRegression  0.806333   0.832956  0.806333  0.802289
